package com.ab.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UploadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadAllPropertiesEquals(Upload expected, Upload actual) {
        assertUploadAutoGeneratedPropertiesEquals(expected, actual);
        assertUploadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadAllUpdatablePropertiesEquals(Upload expected, Upload actual) {
        assertUploadUpdatableFieldsEquals(expected, actual);
        assertUploadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadAutoGeneratedPropertiesEquals(Upload expected, Upload actual) {
        assertThat(expected)
            .as("Verify Upload auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadUpdatableFieldsEquals(Upload expected, Upload actual) {
        assertThat(expected)
            .as("Verify Upload relevant properties")
            .satisfies(e -> assertThat(e.getFile()).as("check file").isEqualTo(actual.getFile()))
            .satisfies(e -> assertThat(e.getFileContentType()).as("check file contenty type").isEqualTo(actual.getFileContentType()))
            .satisfies(e -> assertThat(e.getFileType()).as("check fileType").isEqualTo(actual.getFileType()))
            .satisfies(e -> assertThat(e.getUploadDate()).as("check uploadDate").isEqualTo(actual.getUploadDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadUpdatableRelationshipsEquals(Upload expected, Upload actual) {
        assertThat(expected)
            .as("Verify Upload relationships")
            .satisfies(e -> assertThat(e.getUserProfile()).as("check userProfile").isEqualTo(actual.getUserProfile()));
    }
}
