package com.ab.hr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserSkillAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSkillAllPropertiesEquals(UserSkill expected, UserSkill actual) {
        assertUserSkillAutoGeneratedPropertiesEquals(expected, actual);
        assertUserSkillAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSkillAllUpdatablePropertiesEquals(UserSkill expected, UserSkill actual) {
        assertUserSkillUpdatableFieldsEquals(expected, actual);
        assertUserSkillUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSkillAutoGeneratedPropertiesEquals(UserSkill expected, UserSkill actual) {
        assertThat(expected)
            .as("Verify UserSkill auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSkillUpdatableFieldsEquals(UserSkill expected, UserSkill actual) {
        assertThat(expected)
            .as("Verify UserSkill relevant properties")
            .satisfies(e -> assertThat(e.getYear()).as("check year").isEqualTo(actual.getYear()))
            .satisfies(e -> assertThat(e.getLevel()).as("check level").isEqualTo(actual.getLevel()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()))
            .satisfies(e -> assertThat(e.getDeletedAt()).as("check deletedAt").isEqualTo(actual.getDeletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSkillUpdatableRelationshipsEquals(UserSkill expected, UserSkill actual) {
        assertThat(expected)
            .as("Verify UserSkill relationships")
            .satisfies(e -> assertThat(e.getSkill()).as("check skill").isEqualTo(actual.getSkill()));
    }
}
